version: '3.8'  # 使用的 Docker Compose 文件版本

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # 指定 Dockerfile 的路径
      args:
        GIT_COMMIT_SHA: ${GIT_COMMIT_SHA:-default}
        GIT_TAG: ${GIT_TAG:-latest}  # 传递构建参数
        NEXT_OPEN_TELEMETRY_ENABLED: "true"
        ENVS_PRESET: ""
    ports:
      - "3000:3000"  # 映射容器的端口到主机
    environment:
      - NODE_ENV=production  # 设置环境变量
    volumes:
      - .:/app  # 挂载当前目录到容器中的 /app
    command: ["node", "server.js"]  # 运行的命令

  # 你可以在这里添加其他服务，例如数据库、缓存等